---
- import_tasks: preflight.yml
  tags:
    - binary_install
    - binary_configure
    - binary_run

- import_tasks: install.yml
  become: true
  when: (not __binary_is_installed.stat.exists) or (binary_version not in __binary_current_version_output)
  tags:
    - binary_install

- import_tasks: configure.yml
  become: true
  tags:
    - binary_configure

- name: Ensure binary is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: "{{ binary_name }}"
    enabled: true
    state: started
  tags:
    - binary_run
